# Generated by Django 5.0.1 on 2024-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Date_Of_Birth', models.IntegerField(null=True)),
                ('Education', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Conatact_Number', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
