# Generated by Django 5.0.1 on 2024-02-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='Status',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
