# Generated by Django 5.0.1 on 2024-02-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_regmodel_usertype_usermodel_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='Status',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
