# Generated by Django 5.0.1 on 2024-02-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0006_usermodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Category', models.CharField(max_length=100)),
                ('Job_Name', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=50)),
                ('Job_Details', models.CharField(max_length=50)),
                ('Last_Date_For_Application', models.CharField(max_length=50)),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeapp.regmodel')),
            ],
        ),
    ]
