# Generated by Django 5.0.1 on 2024-02-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_vacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='VacancyModel',
        ),
    ]
