# Generated by Django 5.0.1 on 2024-02-24 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_alter_vacancymodel_compid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancymodel',
            old_name='compid',
            new_name='regid',
        ),
    ]
