# Generated by Django 5.0.1 on 2024-03-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0012_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='canacel',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
