# Generated by Django 5.0.1 on 2024-03-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0013_jobapplication_canacel_alter_jobapplication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDetails',
            fields=[
                ('intrw_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('interviewDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumeapp.jobapplication')),
            ],
        ),
    ]
